title:            Jyothir Aditya
description:      An Deep Learning site
url:              https://jyoth1raditya.github.io/web/
signoff:          #
disqus_shortname: jyothiraditya
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.
comments: true
links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         GitHub
    url:          https://github.com/jyoth1raditya
    external:     true
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
kramdown:
  input: GFM
  # redcarpet:
  # extensions:
  #   - smart
